// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_a.Data;

namespace Projeto_WDProducers.Migrations
{
    [DbContext(typeof(WDProducersContext))]
    partial class WDProducersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Projeto_a.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nome");

                    b.Property<string>("Sigla")
                        .HasColumnType("longtext")
                        .HasColumnName("Sigla");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia",
                            Sigla = "TI"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Recursos Humando",
                            Sigla = "RH"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Marketing",
                            Sigla = "MKT"
                        });
                });

            modelBuilder.Entity("Projeto_a.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext")
                        .HasColumnName("Foto");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<int>("RG")
                        .HasColumnType("int")
                        .HasColumnName("RG");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Foto = "Pmg",
                            Nome = "Joao",
                            RG = 88888888
                        },
                        new
                        {
                            Id = 2,
                            Foto = "Pmg",
                            Nome = "Maria",
                            RG = 77777777
                        },
                        new
                        {
                            Id = 3,
                            Foto = "Pmg",
                            Nome = "Pedro",
                            RG = 99999999
                        });
                });

            modelBuilder.Entity("Projeto_a.Models.Funcionario", b =>
                {
                    b.HasOne("Projeto_a.Models.Departamento", "Departamento")
                        .WithMany("Funcionario")
                        .HasForeignKey("DepartamentoId");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Projeto_a.Models.Departamento", b =>
                {
                    b.Navigation("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
